CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun --nproc_per_node 4 train_ddp.py \
  --features_dir data_av2/features/ \
  --train_batch_size 32 \
  --val_batch_size 32 \
  --val_interval 1 \
  --train_epoches 50 \
  --data_aug \
  --use_cuda \
  --logger_writer \
  --adv_cfg_path cfg.simpl_av2_cfg \
  --experiment_name av2_dropout0.1_lr_func